export type Vendor = {
  id: string
  name: string
  category: "insurance" | "accessories" | "safety" | "service"
  description: string
  priceRange: string
  distance: string
  rating: number
  reviewCount: number
  location: string
  verified: boolean
  products: string[]
  image: string
}

export const vendors: Vendor[] = [
  // Insurance
  {
    id: "ins-1",
    name: "SecureShield Insurance",
    category: "insurance",
    description: "Comprehensive car insurance with roadside assistance and zero depreciation cover. Quick claim settlement.",
    priceRange: "8,000 - 25,000/yr",
    distance: "1.2 km",
    rating: 4.8,
    reviewCount: 342,
    location: "Andheri West, Mumbai",
    verified: true,
    products: ["Comprehensive Cover", "Third Party", "Zero Depreciation", "Roadside Assistance"],
    image: "/images/hero-car.jpg",
  },
  {
    id: "ins-2",
    name: "DriveGuard Policies",
    category: "insurance",
    description: "Affordable car insurance plans with cashless claim facility at 5,000+ garages nationwide.",
    priceRange: "6,500 - 18,000/yr",
    distance: "3.5 km",
    rating: 4.5,
    reviewCount: 218,
    location: "Bandra East, Mumbai",
    verified: true,
    products: ["Basic Cover", "Comprehensive", "Engine Protect", "Personal Accident"],
    image: "/images/hero-car.jpg",
  },
  {
    id: "ins-3",
    name: "AutoSafe Premium",
    category: "insurance",
    description: "Premium insurance provider with dedicated claim managers and 24/7 support line.",
    priceRange: "12,000 - 35,000/yr",
    distance: "5.1 km",
    rating: 4.9,
    reviewCount: 567,
    location: "Powai, Mumbai",
    verified: true,
    products: ["Premium Cover", "Key Replacement", "Tyre Protect", "Return to Invoice"],
    image: "/images/hero-car.jpg",
  },
  // Accessories
  {
    id: "acc-1",
    name: "AutoStyle Hub",
    category: "accessories",
    description: "Premium car accessories including alloy wheels, seat covers, infotainment systems, and LED lighting.",
    priceRange: "500 - 50,000",
    distance: "2.3 km",
    rating: 4.6,
    reviewCount: 189,
    location: "Kurla, Mumbai",
    verified: true,
    products: ["Alloy Wheels", "Seat Covers", "Infotainment", "LED Lights", "Floor Mats"],
    image: "/images/accessories.jpg",
  },
  {
    id: "acc-2",
    name: "CarMod Pro",
    category: "accessories",
    description: "Custom car modifications and genuine OEM parts. Performance upgrades and aesthetic enhancements.",
    priceRange: "1,000 - 80,000",
    distance: "4.8 km",
    rating: 4.7,
    reviewCount: 275,
    location: "Thane West, Mumbai",
    verified: true,
    products: ["Body Kits", "Exhaust Systems", "Suspension", "Wrap & Paint", "Audio Systems"],
    image: "/images/accessories.jpg",
  },
  {
    id: "acc-3",
    name: "QuickFit Accessories",
    category: "accessories",
    description: "One-stop shop for all car accessories with free installation on selected items.",
    priceRange: "300 - 25,000",
    distance: "1.8 km",
    rating: 4.4,
    reviewCount: 156,
    location: "Dadar, Mumbai",
    verified: false,
    products: ["Car Covers", "Phone Mounts", "Dash Mats", "Window Films", "Perfumes"],
    image: "/images/accessories.jpg",
  },
  // Safety
  {
    id: "saf-1",
    name: "SafeDrive Store",
    category: "safety",
    description: "Complete range of car safety equipment including dashcams, first-aid kits, and emergency tools.",
    priceRange: "500 - 15,000",
    distance: "3.1 km",
    rating: 4.8,
    reviewCount: 204,
    location: "Worli, Mumbai",
    verified: true,
    products: ["Dashcams", "First Aid Kits", "Fire Extinguishers", "Emergency Hammers", "Reflective Vests"],
    image: "/images/hero-car.jpg",
  },
  {
    id: "saf-2",
    name: "GuardianAuto Safety",
    category: "safety",
    description: "Premium safety products with installation services. GPS trackers, TPMS, and blind-spot mirrors.",
    priceRange: "1,000 - 30,000",
    distance: "6.2 km",
    rating: 4.5,
    reviewCount: 132,
    location: "Goregaon, Mumbai",
    verified: true,
    products: ["GPS Trackers", "TPMS", "Blind Spot Mirrors", "Reverse Cameras", "Parking Sensors"],
    image: "/images/hero-car.jpg",
  },
  // Service Centers
  {
    id: "srv-1",
    name: "ProMech Auto Care",
    category: "service",
    description: "Multi-brand service center with certified mechanics. Full range of maintenance, repair, and detailing.",
    priceRange: "1,500 - 20,000",
    distance: "2.0 km",
    rating: 4.7,
    reviewCount: 489,
    location: "Lower Parel, Mumbai",
    verified: true,
    products: ["General Service", "AC Repair", "Denting & Painting", "Detailing", "Wheel Alignment"],
    image: "/images/about-team.jpg",
  },
  {
    id: "srv-2",
    name: "SpeedFix Garage",
    category: "service",
    description: "Quick and reliable car repairs with transparent pricing. Specializing in engine and transmission work.",
    priceRange: "800 - 15,000",
    distance: "4.5 km",
    rating: 4.4,
    reviewCount: 312,
    location: "Malad West, Mumbai",
    verified: true,
    products: ["Engine Repair", "Transmission", "Brake Service", "Electrical", "Diagnostics"],
    image: "/images/about-team.jpg",
  },
  {
    id: "srv-3",
    name: "Elite Car Spa",
    category: "service",
    description: "Premium car washing, ceramic coating, and interior deep cleaning services with pickup and drop.",
    priceRange: "500 - 25,000",
    distance: "1.5 km",
    rating: 4.9,
    reviewCount: 267,
    location: "Juhu, Mumbai",
    verified: true,
    products: ["Car Wash", "Ceramic Coating", "Interior Cleaning", "PPF", "Polishing"],
    image: "/images/about-team.jpg",
  },
]
